routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

Route::resource('products', 'ProductController')->only(['index','edit', 'create', 'store']);
Route::resource('product-types', 'ProductTypeController')->except(['show', 'destroy']);

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{

    protected $fillable = ['name', 'attributes'];

    protected $casts = [
        'attributes'=> 'array'
    ];

    public function type()
    {
        return $this->belongsTo(ProductType::class, 'product_type_id');
    }

    public function scopeOfType($query, $typeId)
    {
        return $query->whereHas('type', function ($q) use ($typeId) {
            $q->where('id', $typeId);
        });
    }
}

app/Models/ProductType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ProductType extends Model
{
    protected $fillable = ['name', 'attributes'];

    protected $casts = [
        'attributes'=> 'array'
    ];

    public function products()
    {
        return $this->hasMany(Product::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use App\Models\ProductType;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;

class ProductController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $products = Cache::remember('products', Carbon::now()->addMinute(30), function () {
            return Product::with('type')->get();
        });

        return view('products.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $productTypes = Cache::remember('productTypes', Carbon::now()->addMinute(30), function () {
            return ProductType::all(['id', 'name', 'attributes']);
        });
        $product = new Product();

        return view('products.create', compact(['productTypes', 'product']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function store(Request $request)
    {
        $attr    = $request->all();
        $type    = ProductType::find($attr['type']);
        $product = new Product;
        $product->fill([
            'name'       => $attr['name'],
            'attributes' => $attr['attributes'],
        ]);
        $type->products()->save($product);
        Cache::forget('products');

        return response()->json(['data' => $product]);
    }
}

app/Http/Controllers/ProductTypeController.php
<?php

namespace App\Http\Controllers;

use App\Models\ProductType;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;

class ProductTypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $productTypes = Cache::remember('productTypes', Carbon::now()->addMinutes(30), function(){
            return ProductType::all();
        });

        return view('product-types.index', compact('productTypes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('product-types.create', ['productType' => new ProductType()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        ProductType::create($request->only(['name', 'attributes']));
        Cache::forget('productTypes');

        return redirect()->route('product-types.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        $productType = ProductType::findOrFail($id);

        return view('product-types.create', compact('productType'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {
        $productType = ProductType::findOrFail($id);
        $productType->update($request->only(['name', 'attributes']));
        Cache::forget('productTypes');

        return redirect()->route('product-types.index');
    }

}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    @component('components.menu-item', ['route'=>'products', 'routeName'=>'products.index', 'item'=>'Products'])
                    @endcomponent
                    @component('components.menu-item', ['route'=>'product-types', 'routeName'=>'product-types.index', 'item'=>'Product Types'])
                    @endcomponent
                </ul>
            </div>
        </div>
    </nav>

    <main class="py-4">
        <div class="container">
            @yield('content')
        </div>
    </main>
</div>
</body>
</html>

resources/views/product-types/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="product-types">
        <div class="row justify-content-center">
            <div class="col-md-8 offset-2">
                @if($productType->exists)
                    <h2>Update Product Types</h2>
                @else
                    <h2>Add Product Types</h2>
                @endif
                <form action="{{$productType->exists ? route('product-types.update', ['product_type'=>$productType->id]): route('product-types.store')}}"
                      method="POST" role="form">
                    {{csrf_field()}}
                    @if($productType->exists)
                        {{method_field('PUT')}}
                    @endif

                    <div class="form-group">
                        <label for="type-name">Name*:</label>
                        <input type="text" class="form-control" id="type-name"
                               placeholder="Enter Name" name="name"
                               value="{{$productType->exists? $productType->name:''}}" required>
                    </div>
                    <div id="form-wrapper" class="attribute-set mb-2">
                        <h4>Attributes*:</h4>
                        @if($productType->exists)
                            @foreach($productType->attributes as $attributes)
                                <div class="form-row">
                                    @foreach($attributes as $key=>$value)
                                        <div class="col">
                                            <input type="text" class="form-control"
                                                   name="attributes[{{$loop->parent->index}}][{{$key}}]"
                                                   value="{{$value}}" placeholder="Attribute Key">
                                        </div>
                                    @endforeach
                                    <i class="far fa-minus-square fa-lg text-danger remove-icon"></i>
                                </div>

                            @endforeach
                        @else
                            @for($i=0; $i < 2; $i++)
                                <div class="form-row">
                                    <div class="col">
                                        <input type="text" class="form-control" name="attributes[{{$i}}][key]"
                                               value="" placeholder="Attribute Key">
                                    </div>
                                    <div class="col">
                                        <input type="text" class="form-control" name="attributes[{{$i}}][type]"
                                               placeholder="Attribute Type">
                                    </div>
                                </div>
                            @endfor
                        @endif
                    </div>
                    <i id="add-new-attribute" class="far fa-plus-square fa-lg text-success cursor-pointer"></i>
                    <br>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/product-types/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="product-types">
        <div class="row justify-content-center">
            <div class="col-md-8 offset-2">
                <div class="d-flex justify-content-between align-items-center">
                    <h2>Product Types List</h2>
                    <a href="{{route('product-types.create')}}">
                        <i class="far fa-plus-square fa-lg text-success"></i>
                    </a>
                </div>
                @empty(!count($productTypes))
                    @foreach($productTypes as $type)
                        <div class="card mb-1">
                            <div class="card-body">
                                <div class="d-flex justify-content-between">
                                    <h4>{{$type->name}}</h4>
                                    <a href="{{route('product-types.edit', ['product_type'=>$type->id])}}">
                                        <i class="fas fa-pen"></i>
                                    </a>
                                </div>
                                <h5>Attributes</h5>
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th scope="col">Name</th>
                                        <th scope="col">Type</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($type->attributes as $attributes)
                                        <tr>
                                            @foreach($attributes as $attr)
                                                <td>{{$attr}}</td>
                                            @endforeach
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>

                            </div>
                        </div>
                    @endforeach
                @else
                    <h3>Product Types Not Found</h3>
                @endempty

            </div>
        </div>
    </div>
@endsection

resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="products">
        <div class="row justify-content-center">
            <div class="col-md-8 offset-2">
                <create-new-product-component :product="{{$product}}"
                                              :product-types="{{$productTypes}}"/>
            </div>
        </div>
    </div>
@endsection

resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-8 offset-2">
            <div class="d-flex justify-content-between">
                <h2>Products List</h2>
                <a href="{{route('products.create')}}">
                    <i class="far fa-plus-square fa-lg text-success"></i>
                </a>
            </div>
            @empty(!count($products))
                @foreach($products as $product)
                    <div class="card mb-1">
                        <div class="card-body">
                            <div class="d-flex justify-content-between">
                                <h4>{{$product->name}}</h4>
                                <a style="display: block" href="{{route('products.edit', ['product'=>$product->id])}}">
                                    <i class="fas fa-pen fa-lg"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                @endforeach
            @else
                <h3>Products Not Found</h3>
            @endempty
        </div>
    </div>
@endsection